import jsPDF from "jspdf";
import autoTable from "jspdf-autotable";
import { format } from "date-fns";
import { PECS_PHASES } from "@/types";
import type { ProgressReportData, PhaseMasteryReportData } from "./types";

// Colors
const PRIMARY_COLOR: [number, number, number] = [34, 139, 34]; // Forest green
const SECONDARY_COLOR: [number, number, number] = [100, 100, 100];
const SUCCESS_COLOR: [number, number, number] = [34, 197, 94];
const WARNING_COLOR: [number, number, number] = [234, 179, 8];

// Helper to add header to each page
function addHeader(doc: jsPDF, title: string, childName: string) {
  const pageWidth = doc.internal.pageSize.getWidth();

  // Title bar
  doc.setFillColor(...PRIMARY_COLOR);
  doc.rect(0, 0, pageWidth, 25, "F");

  // Title text
  doc.setTextColor(255, 255, 255);
  doc.setFontSize(18);
  doc.setFont("helvetica", "bold");
  doc.text(title, 14, 16);

  // Child name on right
  doc.setFontSize(12);
  doc.setFont("helvetica", "normal");
  doc.text(childName, pageWidth - 14, 16, { align: "right" });

  // Reset text color
  doc.setTextColor(0, 0, 0);
}

// Helper to add footer
function addFooter(doc: jsPDF, pageNumber: number, totalPages: number) {
  const pageWidth = doc.internal.pageSize.getWidth();
  const pageHeight = doc.internal.pageSize.getHeight();

  doc.setFontSize(9);
  doc.setTextColor(...SECONDARY_COLOR);
  doc.text(
    `Generated by PECS Learn - ${format(new Date(), "MMM d, yyyy 'at' h:mm a")}`,
    14,
    pageHeight - 10
  );
  doc.text(
    `Page ${pageNumber} of ${totalPages}`,
    pageWidth - 14,
    pageHeight - 10,
    { align: "right" }
  );
}

// Generate Weekly Progress Report
export function generateWeeklyProgressReport(data: ProgressReportData): jsPDF {
  const doc = new jsPDF();
  const pageWidth = doc.internal.pageSize.getWidth();

  addHeader(doc, "Weekly Progress Report", data.child.name);

  let yPos = 35;

  // Report period
  doc.setFontSize(11);
  doc.setTextColor(...SECONDARY_COLOR);
  doc.text(
    `Report Period: ${format(new Date(data.reportPeriod.start), "MMM d")} - ${format(new Date(data.reportPeriod.end), "MMM d, yyyy")}`,
    14,
    yPos
  );
  yPos += 12;

  // Summary section
  doc.setFontSize(14);
  doc.setFont("helvetica", "bold");
  doc.setTextColor(0, 0, 0);
  doc.text("Weekly Summary", 14, yPos);
  yPos += 8;

  // Summary stats in a grid
  const stats = [
    { label: "Sessions", value: data.weeklyMetrics.totalSessions.toString() },
    { label: "Activities", value: data.weeklyMetrics.totalActivities.toString() },
    { label: "Success Rate", value: `${Math.round(data.weeklyMetrics.successRate)}%` },
    { label: "Days Active", value: `${data.weeklyMetrics.daysActive}/7` },
    { label: "Streak", value: `${data.weeklyMetrics.streakDays} days` },
    { label: "Avg Duration", value: `${Math.round(data.weeklyMetrics.avgSessionDuration)} min` },
  ];

  const colWidth = (pageWidth - 28) / 3;
  stats.forEach((stat, index) => {
    const col = index % 3;
    const row = Math.floor(index / 3);
    const x = 14 + col * colWidth;
    const y = yPos + row * 20;

    // Value
    doc.setFontSize(20);
    doc.setFont("helvetica", "bold");
    doc.setTextColor(...PRIMARY_COLOR);
    doc.text(stat.value, x, y + 6);

    // Label
    doc.setFontSize(10);
    doc.setFont("helvetica", "normal");
    doc.setTextColor(...SECONDARY_COLOR);
    doc.text(stat.label, x, y + 12);
  });
  yPos += 50;

  // Phase Progress section
  doc.setFontSize(14);
  doc.setFont("helvetica", "bold");
  doc.setTextColor(0, 0, 0);
  doc.text("Phase Progress", 14, yPos);
  yPos += 5;

  const phaseTableData = data.weeklyMetrics.phaseProgress.map((p) => {
    const phaseInfo = PECS_PHASES.find((ph) => ph.id === p.phase);
    return [
      `Phase ${p.phase}`,
      phaseInfo?.name || "",
      p.sessionsCompleted.toString(),
      `${Math.round(p.successRate)}%`,
      p.status.replace("_", " ").replace(/\b\w/g, (c) => c.toUpperCase()),
    ];
  });

  autoTable(doc, {
    startY: yPos,
    head: [["Phase", "Name", "Sessions", "Success", "Status"]],
    body: phaseTableData,
    theme: "striped",
    headStyles: {
      fillColor: PRIMARY_COLOR,
      textColor: [255, 255, 255],
      fontStyle: "bold",
    },
    styles: {
      fontSize: 10,
    },
    columnStyles: {
      0: { cellWidth: 25 },
      1: { cellWidth: 50 },
      4: { cellWidth: 35 },
    },
  });

  yPos = (doc as jsPDF & { lastAutoTable: { finalY: number } }).lastAutoTable.finalY + 15;

  // Recent Sessions section
  if (yPos > 220) {
    doc.addPage();
    addHeader(doc, "Weekly Progress Report", data.child.name);
    yPos = 35;
  }

  doc.setFontSize(14);
  doc.setFont("helvetica", "bold");
  doc.setTextColor(0, 0, 0);
  doc.text("Session Details", 14, yPos);
  yPos += 5;

  const sessionTableData = data.sessions.slice(0, 10).map((s) => [
    format(new Date(s.date), "MMM d"),
    `Phase ${s.phase}`,
    `${s.duration} min`,
    s.activitiesCompleted.toString(),
    `${Math.round(s.successRate)}%`,
  ]);

  autoTable(doc, {
    startY: yPos,
    head: [["Date", "Phase", "Duration", "Activities", "Success"]],
    body: sessionTableData,
    theme: "striped",
    headStyles: {
      fillColor: PRIMARY_COLOR,
      textColor: [255, 255, 255],
      fontStyle: "bold",
    },
    styles: {
      fontSize: 10,
    },
  });

  yPos = (doc as jsPDF & { lastAutoTable: { finalY: number } }).lastAutoTable.finalY + 15;

  // Achievements section
  if (data.achievements.length > 0) {
    if (yPos > 240) {
      doc.addPage();
      addHeader(doc, "Weekly Progress Report", data.child.name);
      yPos = 35;
    }

    doc.setFontSize(14);
    doc.setFont("helvetica", "bold");
    doc.setTextColor(0, 0, 0);
    doc.text("Achievements Earned", 14, yPos);
    yPos += 8;

    doc.setFontSize(11);
    doc.setFont("helvetica", "normal");
    data.achievements.forEach((achievement) => {
      doc.text(`• ${achievement.name}`, 18, yPos);
      yPos += 6;
    });
    yPos += 8;
  }

  // Recommendations section
  if (data.recommendations.length > 0) {
    if (yPos > 250) {
      doc.addPage();
      addHeader(doc, "Weekly Progress Report", data.child.name);
      yPos = 35;
    }

    doc.setFontSize(14);
    doc.setFont("helvetica", "bold");
    doc.setTextColor(0, 0, 0);
    doc.text("Recommendations", 14, yPos);
    yPos += 8;

    doc.setFontSize(11);
    doc.setFont("helvetica", "normal");
    doc.setTextColor(...SECONDARY_COLOR);
    data.recommendations.forEach((rec) => {
      const lines = doc.splitTextToSize(`• ${rec}`, pageWidth - 28);
      doc.text(lines, 18, yPos);
      yPos += lines.length * 5 + 3;
    });
  }

  // Add footer to all pages
  const totalPages = doc.getNumberOfPages();
  for (let i = 1; i <= totalPages; i++) {
    doc.setPage(i);
    addFooter(doc, i, totalPages);
  }

  return doc;
}

// Generate Phase Mastery Report
export function generatePhaseMasteryReport(data: PhaseMasteryReportData): jsPDF {
  const doc = new jsPDF();
  const pageWidth = doc.internal.pageSize.getWidth();

  addHeader(doc, `Phase ${data.phase} Mastery Report`, data.child.name);

  let yPos = 35;

  // Phase info
  doc.setFontSize(16);
  doc.setFont("helvetica", "bold");
  doc.setTextColor(...PRIMARY_COLOR);
  doc.text(data.phaseName, 14, yPos);
  yPos += 10;

  // Status badge
  const isMastered = !!data.masteryDate;
  doc.setFillColor(...(isMastered ? SUCCESS_COLOR : WARNING_COLOR));
  doc.roundedRect(14, yPos - 5, 50, 12, 2, 2, "F");
  doc.setFontSize(10);
  doc.setFont("helvetica", "bold");
  doc.setTextColor(255, 255, 255);
  doc.text(isMastered ? "MASTERED" : "IN PROGRESS", 18, yPos + 3);
  yPos += 20;

  // Timeline
  doc.setFontSize(11);
  doc.setFont("helvetica", "normal");
  doc.setTextColor(0, 0, 0);
  doc.text(`Started: ${format(new Date(data.startDate), "MMMM d, yyyy")}`, 14, yPos);
  if (data.masteryDate) {
    doc.text(
      `Mastered: ${format(new Date(data.masteryDate), "MMMM d, yyyy")}`,
      100,
      yPos
    );
  }
  yPos += 15;

  // Summary stats
  doc.setFontSize(14);
  doc.setFont("helvetica", "bold");
  doc.text("Summary Statistics", 14, yPos);
  yPos += 10;

  const stats = [
    ["Total Sessions", data.totalSessions.toString()],
    ["Total Activities", data.totalActivities.toString()],
    ["Final Success Rate", `${Math.round(data.finalSuccessRate)}%`],
  ];

  stats.forEach(([label, value]) => {
    doc.setFontSize(11);
    doc.setFont("helvetica", "normal");
    doc.setTextColor(...SECONDARY_COLOR);
    doc.text(label + ":", 14, yPos);
    doc.setTextColor(0, 0, 0);
    doc.setFont("helvetica", "bold");
    doc.text(value, 60, yPos);
    yPos += 7;
  });
  yPos += 10;

  // Progress chart (simplified bar representation)
  if (data.progressOverTime.length > 0) {
    doc.setFontSize(14);
    doc.setFont("helvetica", "bold");
    doc.setTextColor(0, 0, 0);
    doc.text("Progress Over Time", 14, yPos);
    yPos += 10;

    const chartWidth = pageWidth - 28;
    const chartHeight = 40;
    const barWidth = Math.min(20, chartWidth / data.progressOverTime.length - 2);

    // Draw axis
    doc.setDrawColor(...SECONDARY_COLOR);
    doc.line(14, yPos + chartHeight, 14 + chartWidth, yPos + chartHeight);

    // Draw bars
    data.progressOverTime.forEach((point, index) => {
      const barHeight = (point.successRate / 100) * chartHeight;
      const x = 14 + index * (barWidth + 2);

      // Bar
      doc.setFillColor(...PRIMARY_COLOR);
      doc.rect(x, yPos + chartHeight - barHeight, barWidth, barHeight, "F");

      // Label
      doc.setFontSize(7);
      doc.setTextColor(...SECONDARY_COLOR);
      doc.text(
        format(new Date(point.date), "M/d"),
        x + barWidth / 2,
        yPos + chartHeight + 5,
        { align: "center" }
      );
    });

    // Y-axis labels
    doc.setFontSize(8);
    doc.text("100%", 10, yPos + 2, { align: "right" });
    doc.text("50%", 10, yPos + chartHeight / 2, { align: "right" });
    doc.text("0%", 10, yPos + chartHeight, { align: "right" });

    yPos += chartHeight + 20;
  }

  // Skills acquired
  if (data.skillsAcquired.length > 0) {
    doc.setFontSize(14);
    doc.setFont("helvetica", "bold");
    doc.setTextColor(0, 0, 0);
    doc.text("Skills Acquired", 14, yPos);
    yPos += 8;

    doc.setFontSize(11);
    doc.setFont("helvetica", "normal");
    data.skillsAcquired.forEach((skill) => {
      doc.setTextColor(...SUCCESS_COLOR);
      doc.text("✓", 14, yPos);
      doc.setTextColor(0, 0, 0);
      doc.text(skill, 22, yPos);
      yPos += 6;
    });
    yPos += 8;
  }

  // Notes
  if (data.notes) {
    if (yPos > 240) {
      doc.addPage();
      addHeader(doc, `Phase ${data.phase} Mastery Report`, data.child.name);
      yPos = 35;
    }

    doc.setFontSize(14);
    doc.setFont("helvetica", "bold");
    doc.setTextColor(0, 0, 0);
    doc.text("Notes", 14, yPos);
    yPos += 8;

    doc.setFontSize(11);
    doc.setFont("helvetica", "normal");
    doc.setTextColor(...SECONDARY_COLOR);
    const lines = doc.splitTextToSize(data.notes, pageWidth - 28);
    doc.text(lines, 14, yPos);
  }

  // Add footer
  const totalPages = doc.getNumberOfPages();
  for (let i = 1; i <= totalPages; i++) {
    doc.setPage(i);
    addFooter(doc, i, totalPages);
  }

  return doc;
}

// Download helper
export function downloadPdf(doc: jsPDF, filename: string) {
  doc.save(filename);
}

// Generate blob for preview
export function getPdfBlob(doc: jsPDF): Blob {
  return doc.output("blob");
}
